logging:
  level:
    com.griddynamics.qa.sprimber.lifecycle.TestCaseIlluminator: DEBUG
    com.griddynamics.qa.sprimber.engine.executor: DEBUG
sprimber:
  configuration:
    featurePath: feature/**/*.feature
    tagFilters:
      - "@echo"